
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "../app/styles/progressbar.css"
import { Providers } from "@/store/Providers";
import { Inter } from "next/font/google";
import { Toaster } from "@/components/ui/toaster";

import NProgress from 'nprogress'

export const poppins = Inter({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-poppins",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({ children }: { children: React.ReactNode }) {
  
  return (
    <html lang="fr">
      <head>
      <link
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
          rel="stylesheet"
        />
      </head>
      <body className={`${poppins.variable} font-sans`}>
        <Providers>{children}</Providers>
        <Toaster/>
      </body>
    </html>
  );
}
