"use client";

import React from "react";

const Ticket = () => {
  return (
    <div className="flex flex-col items-center justify-center min-h-screen bg-gray-100 p-5">
      {/* Titre et sous-titre */}
      <h1 className="text-3xl font-bold text-center mb-2">CONCERT TICKET</h1>
      <p className="text-center text-gray-500 mb-4">FULLY EDITABLE TEMPLATE</p>

      {/* Container principal du billet */}
      <div className="relative flex bg-white rounded-2xl shadow-2xl overflow-hidden w-full max-w-3xl">
        
        {/* Partie gauche : Image de l'événement */}
        <div className="w-1/3 relative">
          <img
            src="/Images/Goku.jpg"
            alt="Événement"
            className="w-full h-full object-cover"
          />
          {/* Perforation côté gauche */}
          <div className="absolute -right-3 top-1/2 transform -translate-y-1/2 bg-white w-6 h-6 rounded-full shadow-md"></div>
        </div>

        {/* Partie centrale : Informations de l'événement */}
        <div className="w-2/3 p-6 flex flex-col justify-between relative">
          
          {/* Titre et lieu */}
          <div>
            <h2 className="text-2xl font-bold text-gray-900">TIAKOLA MELO</h2>
            <p className="text-sm text-gray-500 mt-1">Yaoundé</p>
          </div>

          {/* Informations de l'événement en grille pour un rendu plus fun */}
          <div className="mt-4 bg-gray-50 p-4 rounded-md shadow-inner">
            <div className="grid grid-cols-2 gap-x-6 gap-y-3 text-sm">
            <div className="flex items-center">
                <span className="mr-2">👤</span>
                <span className="font-semibold text-gray-700">Name:</span>
                <span className="ml-1 text-gray-600">Chris</span>
              </div>
              
              <div className="flex items-center">
                <span className="mr-2">📅</span>
                <span className="font-semibold text-gray-700">Date:</span>
                <span className="ml-1 text-gray-600">June 24, 2025</span>
              </div>
              <div className="flex items-center">
                <span className="mr-2">⏰</span>
                <span className="font-semibold text-gray-700">Time:</span>
                <span className="ml-1 text-gray-600">8:35 PM</span>
              </div>
              <div className="flex items-center">
                <span className="mr-2">💺</span>
                <span className="font-semibold text-gray-700">Seat:</span>
                <span className="ml-1 text-gray-600">25</span>
              </div>
              <div className="flex items-center">
                <span className="mr-2">💺</span>
                <span className="font-semibold text-gray-700">Totalplace:</span>
                <span className="ml-1 text-gray-600">100</span>
              </div>
            </div>
          </div>

          {/* Séparateur en pointillés */}
          <div className="border-t border-dashed my-4"></div>

          {/* QR Code et tagline */}
          <div className="flex justify-between items-center">
            <div className="w-16 h-16 bg-gray-100 border border-gray-300 flex items-center justify-center rounded-lg shadow-sm">
              <span className="text-xs text-gray-500">QR Code</span>
            </div>
            <p className="text-xs text-gray-500 italic text-right">
              Generated by MboaEvent
            </p>
          </div>

          {/* Perforation côté droit de la partie centrale */}
          <div className="absolute -right-3 top-1/2 transform -translate-y-1/2 bg-white w-6 h-6 rounded-full shadow-md"></div>
        </div>

        {/* Partie droite : Bord vertical avec effet de déchirure */}
        <div
          className="w-12 bg-black flex flex-col justify-center items-center text-white text-xs font-bold tracking-wider relative"
          style={{
            clipPath: `
              polygon(
                100% 0%,
                98% 5%,
                100% 10%,
                98% 15%,
                100% 20%,
                98% 25%,
                100% 30%,
                98% 35%,
                100% 40%,
                98% 45%,
                100% 50%,
                98% 55%,
                100% 60%,
                98% 65%,
                100% 70%,
                98% 75%,
                100% 80%,
                98% 85%,
                100% 90%,
                98% 95%,
                100% 100%,
                0% 100%,
                0% 0%
              )
            `,
          }}
        >
          <span className="-rotate-90 whitespace-nowrap">VIP-VIP-VIP-VIP-VIP-VIP</span>
        </div>
      </div>
    </div>
  );
};

export default Ticket;
